name: Check Regex Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:

jobs:
  run_bash_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Web
      run: |
        cp regex.yaml REx/src/assets
        cd REx
        npm install --force
        cp /docs ../
        

    - name: Install yq
      run: |
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq

    - name: Run exampleMatcher.sh
      run: |
        cd tests/bash
        chmod +x ./exampleMatcher.sh
        ./exampleMatcher.sh
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Run Go module (exampleMatcher.go)
      run: |
        cd tests/go
        go install
        go run exampleMatcher.go