name: Check Regex Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:

jobs:
  run_bash_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yq
      run: pip install yq

    - name: Make exampleMatcher.sh executable
      run: chmod +x tests/bash/exampleMatcher.sh

    - name: Run exampleMatcher.sh
      run: ./tests/bash/exampleMatcher.sh
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Run Go module (exampleMatcher.go)
      run: |
        cd tests/go
        go install
        go run exampleMatcher.go