name: Check Regex Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:

jobs:
  run_bash_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Web
      run: |
        cp regex.yaml REx/src/assets
#        cd REx
#        npm install --legacy-peer-deps
#        npm run build
#        cd ..
#        cp -r REx/docs/ ../
        

    - name: Install yq
      run: |
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq

    - name: Run exampleMatcher.sh
      run: |
        cd tests/bash
        chmod +x ./exampleMatcher.sh
        ./exampleMatcher.sh
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o regexFinder_linux clients/go/regexFinder.go

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o regexFinder_macos clients/go/regexFinder.go

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o regexFinder_windows.exe clients/go/regexFinder.go
 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: regex-finder-artifacts
        path: regexFinder_linux, regexFinder_macos, regexFinder_windows.exe

    - name: Run Go module (exampleMatcher.go)
      run: |
        cd tests/go
        go install
        go run exampleMatcher.go